// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NWE6pQgaY3Xyl9NWUed2EjkF0PjFmo0',
    appId: '1:223065593723:web:3b42d6de679ad88f094fde',
    messagingSenderId: '223065593723',
    projectId: 'petcare-8b71e',
    authDomain: 'petcare-8b71e.firebaseapp.com',
    storageBucket: 'petcare-8b71e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLiuVYZwggELSO0LWfhNXSGo26_ACU2w',
    appId: '1:223065593723:android:148f16ea0fa5f397094fde',
    messagingSenderId: '223065593723',
    projectId: 'petcare-8b71e',
    storageBucket: 'petcare-8b71e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdOeIm8JO129DklL9AAq5_jPFckymVI0A',
    appId: '1:223065593723:ios:326f03a5f3e24132094fde',
    messagingSenderId: '223065593723',
    projectId: 'petcare-8b71e',
    storageBucket: 'petcare-8b71e.firebasestorage.app',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdOeIm8JO129DklL9AAq5_jPFckymVI0A',
    appId: '1:223065593723:ios:326f03a5f3e24132094fde',
    messagingSenderId: '223065593723',
    projectId: 'petcare-8b71e',
    storageBucket: 'petcare-8b71e.firebasestorage.app',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_NWE6pQgaY3Xyl9NWUed2EjkF0PjFmo0',
    appId: '1:223065593723:web:2613746f9f969d93094fde',
    messagingSenderId: '223065593723',
    projectId: 'petcare-8b71e',
    authDomain: 'petcare-8b71e.firebaseapp.com',
    storageBucket: 'petcare-8b71e.firebasestorage.app',
  );
}
